export const defaultGeneralInfo = {
  id: 1,
  product_website_id: null,
  logo: "uploads/media/company-logos/2026/02/image-2026-02-10-063_nJGjKUGk.png",
  logo_dark: "uploads/media/company-logos/2026/02/image-2026-02-23-134_Z5GV256L.png",
  fav_icon: "uploads/media/company-logos/2026/02/image-2026-02-23-134_7B20Ok7y.png",
  logo_square: "uploads/media/company-logos/2026/02/image-2026-02-23-134_UjyJYl0M.png",
  tab_title: null,
  company_name: "BME LIMITED",
  website: "bme.com.bd",
  short_description: "Bme online bangladesh",
  description: null,
  contact: "016365265454",
  email: "bme@gmail.com",
  address: null,
  google_map_link: null,
  play_store_link: null,
  app_store_link: null,
  footer_copyright_text: "copyright @ 2026",
  payment_banner: "uploads/media/company-logos/2026/02/image-2026-02-23-134_TZXNFEFO.png",

  primary_color: "#0B5FAE",
  secondary_color: "#FF8A00",
  tertiary_color: "#F3F8FF",
  title_color: "#071B3A",
  paragraph_color: "#334155",
  border_color: "#D8E4F2",

  meta_title: "BME | Trusted ICT & Office Equipment Supplier in Bangladesh",
  meta_keywords:
    "BME Online Shop, BME Bangladesh, ICT products Bangladesh, office equipment Bangladesh, computer shop Bangladesh, laptop price in Bangladesh, desktop computer Bangladesh, printer price Bangladesh, photocopier machine Bangladesh, scanner price Bangladesh, m",
  meta_description:
    "BME Online Shop is your trusted source for ICT products, computers, and office equipment in Bangladesh with great prices and service.",
  meta_og_title:
    "Upgrade Your Office with BME Online Shop | ICT & Tech Solutions Bangladesh",
  meta_og_image: "uploadsmediaseo-images202603east-resort_AT1t0AEa.jpg",
  meta_og_description:
    "Upgrade your office with BME Online Shop. Shop laptops, printers, CCTV, and more in Bangladesh with great prices and dependable support.",
  custom_css: ".header{}",
  custom_js: "function testc(){}",
  header_script: "function testd(){}",
  footer_script: "<script>\r\n\tfunction teste(){}\r\n</script>",
  facebook: "https://www.facebook.com/comfiloom",
  instagram: "https://www.instagram.com/comfiloom",
  twitter: null,
  linkedin: "https://www.linkedin.com/company/comfi-loom/",
  youtube: "https://www.youtube.com/@comfiloom",
  messenger: null,
  whatsapp: "+8801301884400",
  telegram: null,
  tiktok: "https://www.tiktok.com/@comfiloom",
  pinterest: null,
  viber: null,
  google_analytic_status: 1,
  google_analytic_tracking_id: null,
  google_tag_manager_status: 0,
  google_tag_manager_id: "G-GE4Z5WB008",
  fb_pixel_status: 0,
  fb_pixel_app_id: null,
  fb_test_event_code: null,
  messenger_chat_status: 0,
  fb_page_id: null,
  tawk_chat_status: 0,
  tawk_chat_link: null,
  crisp_chat_status: 0,
  crisp_website_id: "",
  guest_checkout: 1,
  about_us: null,
  created_at: null,
  updated_at: "2026-04-25T10:51:57.000000Z",
  fb_pixel_api_key: "erasad api key",
  is_global_free_shipping: 0,
  is_shipping_charge_by_area: 0,
  is_shipping_charge_by_weight: 0,
  inside_dhaka_shipping_charge: "120.00",
  outside_dhaka_shipping_charge: "250.00",
  is_show_zila: 1,
  is_show_upozilla: 1,
  is_show_thana: 1,
  is_show_post_office: 1,
  is_show_email: 1,
  is_show_store_pickup: 0,
  shipping_charge_note: null,
  banner_template: "v3",
  product_card_template: "v1",
  product_details_template: "v1",
  featured_category_product: "v2",
  blog_card_template: "v1",
  header_template: "v1",
  footer_template: "v1",
  tiktok_pixel_status: 0,
  tiktok_pixel_id: null,
  tiktok_pixel_token: null,
  tiktok_pixel_secret: null,
  sms_provider: "bulksmsbd",
  sms_api_key: null,
  sms_send_to_customer_for_pos: 0,
  sms_send_to_customer_for_ecommerce: 0,
  landing_page_version: "v1",
  invoice_version: "v1",
  support_time: null,

  // New BME theme design token fields
  primary_dark_color: "#0046B8",
  primary_bright_color: "#0057D9",
  accent_color: "#FF8A00",
  accent_soft_color: "#FFF3E0",
  page_background_color: "#F5F7FA",
  card_background_color: "#FFFFFF",
  soft_blue_background_color: "#F3F8FF",
  border_soft_color: "#E8EEF6",
  text_body_color: "#334155",
  text_muted_color: "#64748B",
  text_light_muted_color: "#94A3B8",
  success_color: "#16A34A",
  warning_color: "#F59E0B",
  danger_color: "#DC2626",
  button_primary_color: "#0057D9",
  button_primary_hover_color: "#0046B8",
  button_text_color: "#FFFFFF",
  outline_button_border_color: "#0B5FAE",
  outline_button_hover_background_color: "#EEF5FF",
  mega_menu_hover_background_color: "#EEF5FF",
  discount_color: "#FF8A00",
  rating_star_color: "#F59E0B",
};
